// <auto-generated />
using DAL.EfStructures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.EfStructures.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220902141723_DepartmentNameAsPK")]
    partial class DepartmentNameAsPK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Department", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Name");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.Models.DepartmentMap", b =>
                {
                    b.Property<string>("DepartmentName")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubdepartmentName")
                        .HasColumnType("character varying(50)");

                    b.HasKey("DepartmentName", "SubdepartmentName");

                    b.HasIndex("SubdepartmentName");

                    b.ToTable("DepartmentMap");
                });

            modelBuilder.Entity("Domain.Models.DepartmentMap", b =>
                {
                    b.HasOne("Domain.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("SubdepartmentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
